services:
  web:
    build: .
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl
    depends_on:
      - web

  db:
    image: postgres:17
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_DB
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
